### PR TITLE
Initial commit for the pysteps project

### PR DESCRIPTION
**Pull request by dnerini**

### CODE REVIEW

**Comment by scollis** [comment]
WOW! This is super cool! Thanks @dnerini

**Comment by scollis** [comment]
It takes some time (I think @heistermann can confirm) for the page to refresh.. will check later

**Comment by dnerini** [comment]
I've checked now and the new page is there, many thanks @scollis !

**Comment by zssherman** [comment]
Hi @dnerini , I would possibly suggest too, adding the line:
```* [Pysteps]({filename}../posts/pysteps.md)```

Under the related projects section in content/pages/projects.md

**Comment by zssherman** [comment]
Just realized the pull request was merged, my bad :)

**Comment by dnerini** [comment]
@zssherman I've just opened a new pull request to add the line to content/posts/pysteps.md . Hope this is fine.

**Pull request merged**
