### PR TITLE
Request to include PyScanCf in the open radar science

### PR DESCRIPTION
**Pull request by syedhamidali**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@syedhamidali The build is currently broken due to changes to `pelican` (our site builder). This takes more time than expected. Sorry for the inconvenience.

**Comment by syedhamidali** [comment]
Hi @kmuehlbauer, I thought I did something wrong while writing a script. Anyways, thanks for the info.

**Comment by kmuehlbauer** [comment]
@syedhamidali No, your changes seem OK to me, but let's fix the issue before pulling this in. Might take a while, though.

**Comment by kmuehlbauer** [comment]
@syedhamidali I've disabled some breaking plugins for the moment, so that it builds correctly.

**Comment by kmuehlbauer** [comment]
@syedhamidali Success! https://openradarscience.org/2022/07/pyscancf/

**Pull request merged**
