### PR TITLE
added Pyrad description

### PR DESCRIPTION
**Pull request by jfigui**
Dear masters of the open radar,

I added a description of Pyrad. Could we merge it by the beginning of next week?

Many thanks,

Jordi

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@jfigui Travis seems not get the hook anymore. Not sure why this is, but maybe we have run out of credits. So I'll move the CI to GHA the next days.

**Comment by jfigui** [comment]
@kmuehlbauer , we moved everything to GHA some time ago and it worked very well. Since I only added a page can you review it manually and eventually merge? I would like Pyrad to be there before my presentation in Italy next week.
Also, it would be nice to keep the page a bit more alive. (add LROSE, for example). I think it is a good communication platform.

**Comment by kmuehlbauer** [comment]
> Also, it would be nice to keep the page a bit more alive. (add LROSE, for example). I think it is a good communication platform.

@jfigui I do not have the cycles to consistently add to the page. But the community can add things via PR. Also any other contributions are very welcome, always.

**Comment by kmuehlbauer** [comment]
@jfigui I've moved the CI to GHA and added an entry to the `projects.md` page. This should be online in a few minutes. Good luck with the presentation in Italy! :+1:

**Comment by jfigui** [comment]
Thanks a lot! That is perfect. Of course keeping the page alive should come from the community not from a single individual. It would be good if we keep the news section more active by putting there announcements of new releases, presentations, etc.
The point is to keep the page up in the Google search so that people interested in open weather radar has an easy to find landing place and they are given a view as broad as possible of what it is in offer.
Do you think we can find a less cumbersome process than a pull request to add news for example?

**Pull request merged**
